export type CardDirection = "up" | "down" | "left" | "right";

export const DIRECTION_LABELS: Record<CardDirection, string> = {
  up: "위",
  down: "아래",
  left: "왼쪽",
  right: "오른쪽",
};

export interface TarotCard {
  number: number;
  nameEn: string;
  nameKo: string;
  keyword: string;
  fortunes: Record<CardDirection, string>;
}

export const TAROT_CARDS: TarotCard[] = [
  {
    number: 0,
    nameEn: "The Fool",
    nameKo: "바보",
    keyword: "새로운 시작",
    fortunes: {
      up: "새로운 문이 열립니다 — 두려움 없이 첫걸음을 내디뎌 보세요.",
      down: "지금 이 순간에 집중하면 안정감을 찾을 수 있어요.",
      left: "과거의 경험이 지금의 선택에 힌트를 줍니다.",
      right: "작은 행동 하나가 예상치 못한 변화를 만듭니다.",
    },
  },
  {
    number: 1,
    nameEn: "The Magician",
    nameKo: "마법사",
    keyword: "창조, 의지",
    fortunes: {
      up: "원하는 것을 이룰 힘이 이미 당신 안에 있습니다.",
      down: "지금 가진 것들을 잘 활용하면 충분합니다.",
      left: "예전에 배운 기술이 다시 쓸모를 찾을 시기예요.",
      right: "생각만 하지 말고 지금 바로 시도해 보세요.",
    },
  },
  {
    number: 2,
    nameEn: "The High Priestess",
    nameKo: "여사제",
    keyword: "직관, 신비",
    fortunes: {
      up: "직감이 이끄는 방향으로 한 걸음 나아가 보세요.",
      down: "말보다 침묵 속에서 답을 찾게 될 거예요.",
      left: "무의식 깊은 곳의 기억이 실마리가 됩니다.",
      right: "숨겨진 정보가 곧 드러날 준비를 하고 있어요.",
    },
  },
  {
    number: 3,
    nameEn: "The Empress",
    nameKo: "여황제",
    keyword: "풍요, 성장",
    fortunes: {
      up: "풍요로움이 자라나는 시기, 여유를 가지세요.",
      down: "지금 가꾸고 있는 것들이 튼튼하게 뿌리내리는 중이에요.",
      left: "예전에 심어둔 노력이 결실을 맺을 준비를 합니다.",
      right: "새로운 관계나 기회가 자연스럽게 다가옵니다.",
    },
  },
  {
    number: 4,
    nameEn: "The Emperor",
    nameKo: "황제",
    keyword: "안정, 권위",
    fortunes: {
      up: "체계를 세우면 목표에 더 가까워집니다.",
      down: "흔들리지 않는 기반이 지금의 가장 큰 힘이에요.",
      left: "예전의 원칙이 지금도 여전히 유효합니다.",
      right: "결단력 있게 이끌어야 할 순간이 왔어요.",
    },
  },
  {
    number: 5,
    nameEn: "The Hierophant",
    nameKo: "교황",
    keyword: "전통, 가르침",
    fortunes: {
      up: "배움의 기회를 놓치지 마세요.",
      down: "익숙한 방식이 지금은 가장 안전한 길입니다.",
      left: "오래된 조언 속에 답이 숨어 있을 수 있어요.",
      right: "새로운 규칙이나 방식을 받아들여 보세요.",
    },
  },
  {
    number: 6,
    nameEn: "The Lovers",
    nameKo: "연인",
    keyword: "선택, 관계",
    fortunes: {
      up: "마음이 이끄는 선택이 곧 옳은 선택일 수 있어요.",
      down: "지금의 관계에 집중하면 안정을 찾습니다.",
      left: "예전의 인연이 다시 의미를 갖게 될 수도 있어요.",
      right: "중요한 결정을 내려야 할 시기가 다가옵니다.",
    },
  },
  {
    number: 7,
    nameEn: "The Chariot",
    nameKo: "전차",
    keyword: "의지, 전진",
    fortunes: {
      up: "목표를 향해 거침없이 나아갈 때입니다.",
      down: "속도보다 방향을 먼저 점검해 보세요.",
      left: "지금까지의 노력이 곧 추진력이 됩니다.",
      right: "과감하게 밀어붙이면 원하는 걸 얻을 수 있어요.",
    },
  },
  {
    number: 8,
    nameEn: "Strength",
    nameKo: "힘",
    keyword: "용기, 인내",
    fortunes: {
      up: "부드러움이 강함을 이기는 순간이 옵니다.",
      down: "묵묵히 버티는 힘이 지금 가장 중요해요.",
      left: "예전에 극복했던 어려움이 자신감의 근거가 됩니다.",
      right: "두려움을 마주하면 예상보다 쉽게 풀립니다.",
    },
  },
  {
    number: 9,
    nameEn: "The Hermit",
    nameKo: "은둔자",
    keyword: "성찰, 탐구",
    fortunes: {
      up: "혼자만의 시간이 답을 찾는 데 도움이 됩니다.",
      down: "잠시 멈춰서 지금을 돌아보는 것도 좋아요.",
      left: "지난 경험을 곱씹을 때 통찰이 떠오릅니다.",
      right: "혼자 내린 결정이 의외로 좋은 결과를 가져와요.",
    },
  },
  {
    number: 10,
    nameEn: "Wheel of Fortune",
    nameKo: "운명의 수레바퀴",
    keyword: "전환, 순환",
    fortunes: {
      up: "흐름이 좋은 쪽으로 바뀌고 있습니다.",
      down: "지금의 안정도 결국 순환의 일부예요.",
      left: "예전의 상황이 다시 반복될 조짐이 보입니다.",
      right: "예상치 못한 전환점이 곧 찾아올 수 있어요.",
    },
  },
  {
    number: 11,
    nameEn: "Justice",
    nameKo: "정의",
    keyword: "균형, 인과",
    fortunes: {
      up: "공정한 결과가 곧 따라올 거예요.",
      down: "균형 잡힌 선택이 지금 가장 필요합니다.",
      left: "과거의 행동에 대한 결과가 돌아오는 시기입니다.",
      right: "결단을 내리면 명확한 답을 얻게 됩니다.",
    },
  },
  {
    number: 12,
    nameEn: "The Hanged Man",
    nameKo: "매달린 사람",
    keyword: "관점 전환, 기다림",
    fortunes: {
      up: "관점을 바꿔보면 새로운 게 보일 거예요.",
      down: "지금은 기다림이 최선의 전략입니다.",
      left: "예전엔 몰랐던 걸 다시 보게 될 수 있어요.",
      right: "조급해하지 않는 것이 오히려 도움이 됩니다.",
    },
  },
  {
    number: 13,
    nameEn: "Death",
    nameKo: "죽음",
    keyword: "끝과 시작",
    fortunes: {
      up: "끝난 자리에서 새로운 시작이 열립니다.",
      down: "변화를 받아들이면 마음이 오히려 편해져요.",
      left: "지나간 일에 미련을 두지 않아도 괜찮아요.",
      right: "지금 필요한 건 과감한 정리예요.",
    },
  },
  {
    number: 14,
    nameEn: "Temperance",
    nameKo: "절제",
    keyword: "조화, 균형",
    fortunes: {
      up: "균형을 맞추면 흐름이 자연스러워집니다.",
      down: "서두르지 않아도 결국 조화를 이룰 거예요.",
      left: "예전 방식과 새로운 방식을 함께 써보세요.",
      right: "적당한 타협이 예상보다 좋은 결과를 만듭니다.",
    },
  },
  {
    number: 15,
    nameEn: "The Devil",
    nameKo: "악마",
    keyword: "유혹, 속박",
    fortunes: {
      up: "얽매인 것에서 벗어날 용기가 필요합니다.",
      down: "익숙한 유혹에 흔들리지 않는 게 중요해요.",
      left: "반복되던 습관을 돌아볼 시점이에요.",
      right: "지금이야말로 매듭을 끊어낼 때입니다.",
    },
  },
  {
    number: 16,
    nameEn: "The Tower",
    nameKo: "탑",
    keyword: "급변, 깨달음",
    fortunes: {
      up: "예상 밖의 변화가 결국 더 나은 길을 엽니다.",
      down: "흔들려도 무너지지 않는 게 핵심이에요.",
      left: "이미 예견됐던 균열이 드러나는 시기입니다.",
      right: "갑작스러운 사건이 오히려 전화위복이 될 수 있어요.",
    },
  },
  {
    number: 17,
    nameEn: "The Star",
    nameKo: "별",
    keyword: "희망, 영감",
    fortunes: {
      up: "희망을 잃지 않으면 좋은 신호가 이어집니다.",
      down: "지금의 소망이 조용히 이루어지고 있어요.",
      left: "예전에 품었던 꿈이 다시 떠오를 시점입니다.",
      right: "영감이 떠오르면 바로 행동으로 옮겨보세요.",
    },
  },
  {
    number: 18,
    nameEn: "The Moon",
    nameKo: "달",
    keyword: "불안, 잠재의식",
    fortunes: {
      up: "불안함 속에서도 답은 서서히 드러납니다.",
      down: "확실하지 않아도 지금은 그대로 괜찮아요.",
      left: "무의식 속 감정을 들여다볼 필요가 있어요.",
      right: "혼란스러운 상황이 곧 정리되기 시작합니다.",
    },
  },
  {
    number: 19,
    nameEn: "The Sun",
    nameKo: "태양",
    keyword: "성공, 활력",
    fortunes: {
      up: "밝은 기운이 앞으로의 흐름을 채웁니다.",
      down: "지금 이대로도 충분히 만족스러운 상태예요.",
      left: "예전의 노력이 이제야 빛을 보게 됩니다.",
      right: "자신 있게 나서면 좋은 결과가 따라와요.",
    },
  },
  {
    number: 20,
    nameEn: "Judgement",
    nameKo: "심판",
    keyword: "각성, 부활",
    fortunes: {
      up: "새로운 국면으로 넘어갈 준비가 됐습니다.",
      down: "지금의 선택을 스스로 인정해줘도 괜찮아요.",
      left: "지난 일들을 되돌아보면 답이 명확해집니다.",
      right: "결단의 순간, 자신을 믿고 나아가세요.",
    },
  },
  {
    number: 21,
    nameEn: "The World",
    nameKo: "세계",
    keyword: "완성, 성취",
    fortunes: {
      up: "하나의 여정이 완성되는 순간이 다가옵니다.",
      down: "지금까지 쌓아온 것들이 안정적으로 자리잡습니다.",
      left: "지나온 과정 전체가 지금의 결실을 만들었어요.",
      right: "새로운 챕터로 넘어갈 자신감을 가지세요.",
    },
  },
  {
    number: 22,
    nameEn: "Ace of Wands",
    nameKo: "지팡이 에이스",
    keyword: "새로운 열정",
    fortunes: {
      up: "새로운 열정이 솟아오르며 앞으로 나아갈 힘을 얻습니다.",
      down: "마음속에 품은 의지가 서서히 단단해지고 있어요.",
      left: "예전에 품었던 꿈이 다시 불씨를 지필 준비를 합니다.",
      right: "갑자기 떠오른 아이디어가 새로운 도전으로 이어질 수 있어요.",
    },
  },
  {
    number: 23,
    nameEn: "Two of Wands",
    nameKo: "지팡이 2",
    keyword: "계획, 큰 그림",
    fortunes: {
      up: "더 넓은 세상을 향한 계획이 구체적으로 그려지고 있습니다.",
      down: "지금 서 있는 자리를 다지면 다음 걸음이 훨씬 수월해져요.",
      left: "예전에 세워둔 계획을 다시 점검해볼 시점이에요.",
      right: "새로운 선택지가 눈앞에 나타나 고민이 깊어질 수 있어요.",
    },
  },
  {
    number: 24,
    nameEn: "Three of Wands",
    nameKo: "지팡이 3",
    keyword: "확장, 기대",
    fortunes: {
      up: "노력의 결과가 저 멀리서부터 서서히 다가오고 있습니다.",
      down: "지금의 안정적인 흐름이 앞으로의 확장을 뒷받침해줘요.",
      left: "예전에 뿌린 씨앗이 이제야 자라나는 중이에요.",
      right: "예상보다 빠르게 기회의 문이 열릴 수 있어요.",
    },
  },
  {
    number: 25,
    nameEn: "Four of Wands",
    nameKo: "지팡이 4",
    keyword: "축하, 안정",
    fortunes: {
      up: "함께한 사람들과 기쁨을 나눌 일이 생길 것 같아요.",
      down: "지금의 편안함과 안정감을 충분히 누려도 괜찮습니다.",
      left: "예전부터 쌓아온 관계가 든든한 울타리가 되어줍니다.",
      right: "작은 축하할 일이 예상치 못한 순간에 찾아옵니다.",
    },
  },
  {
    number: 26,
    nameEn: "Five of Wands",
    nameKo: "지팡이 5",
    keyword: "경쟁, 갈등",
    fortunes: {
      up: "크고 작은 부딪힘 속에서도 결국 성장할 기회를 얻습니다.",
      down: "지금의 다툼도 시간이 지나면 자연스레 가라앉을 거예요.",
      left: "예전의 경쟁이 지금의 실력을 만든 밑거름이었어요.",
      right: "갑작스러운 의견 충돌이 오히려 새로운 관점을 열어줍니다.",
    },
  },
  {
    number: 27,
    nameEn: "Six of Wands",
    nameKo: "지팡이 6",
    keyword: "승리, 인정",
    fortunes: {
      up: "그동안의 노력이 주변으로부터 인정받는 순간이 옵니다.",
      down: "스스로 이룬 성과를 자신 있게 받아들여도 좋아요.",
      left: "예전의 도전이 지금의 자신감으로 이어졌습니다.",
      right: "뜻밖의 곳에서 좋은 소식이 날아들 수 있어요.",
    },
  },
  {
    number: 28,
    nameEn: "Seven of Wands",
    nameKo: "지팡이 7",
    keyword: "방어, 소신",
    fortunes: {
      up: "흔들림 없이 자신의 입장을 지켜나가면 좋은 결과가 따라옵니다.",
      down: "지금은 묵묵히 버티는 것만으로도 충분한 힘이 됩니다.",
      left: "예전에 지켜온 원칙이 지금도 여전히 옳았음을 깨닫게 돼요.",
      right: "예상치 못한 도전이 와도 소신껏 맞서면 이겨낼 수 있어요.",
    },
  },
  {
    number: 29,
    nameEn: "Eight of Wands",
    nameKo: "지팡이 8",
    keyword: "속도, 진전",
    fortunes: {
      up: "막혀있던 일들이 한꺼번에 빠르게 풀려나갈 조짐이 보입니다.",
      down: "서두르지 않아도 흐름은 자연스럽게 제 속도를 찾아가요.",
      left: "예전부터 기다려온 소식이 곧 도착할 준비를 하고 있어요.",
      right: "갑작스럽게 일이 진행되며 예상보다 빠른 변화가 찾아옵니다.",
    },
  },
  {
    number: 30,
    nameEn: "Nine of Wands",
    nameKo: "지팡이 9",
    keyword: "인내, 방어",
    fortunes: {
      up: "지쳐 보여도 마지막 한 걸음만 더 내디디면 결실을 맺어요.",
      down: "지금까지 버텨온 스스로를 다독여줄 필요가 있습니다.",
      left: "예전의 시련이 지금의 단단함을 만들어줬어요.",
      right: "예상 밖의 지원군이 나타나 힘을 보태줄 수 있어요.",
    },
  },
  {
    number: 31,
    nameEn: "Ten of Wands",
    nameKo: "지팡이 10",
    keyword: "부담, 책임",
    fortunes: {
      up: "짊어진 짐이 무거워도 곧 내려놓을 순간이 다가옵니다.",
      down: "지금의 책임감이 훗날 든든한 자산이 되어줄 거예요.",
      left: "예전부터 떠안아온 부담을 조금씩 덜어내도 괜찮습니다.",
      right: "갑자기 늘어난 일들도 하나씩 처리하다 보면 가벼워져요.",
    },
  },
  {
    number: 32,
    nameEn: "Page of Wands",
    nameKo: "지팡이 시종",
    keyword: "호기심, 소식",
    fortunes: {
      up: "새로운 소식이나 제안이 설렘을 안고 찾아올 수 있어요.",
      down: "지금 품은 호기심을 천천히 키워나가도 좋습니다.",
      left: "예전에 배운 것이 다시 쓸모를 찾을 시기예요.",
      right: "예상치 못한 만남이 새로운 배움으로 이어질 수 있어요.",
    },
  },
  {
    number: 33,
    nameEn: "Knight of Wands",
    nameKo: "지팡이 기사",
    keyword: "모험, 추진력",
    fortunes: {
      up: "망설임 없이 뛰어들면 생각보다 좋은 결과를 얻을 수 있어요.",
      down: "지금은 속도를 조절하며 방향을 다시 살펴봐도 좋습니다.",
      left: "예전의 과감한 선택이 지금의 추진력으로 남아있어요.",
      right: "갑작스러운 제안이나 여행이 활력을 불어넣어 줄 수 있어요.",
    },
  },
  {
    number: 34,
    nameEn: "Queen of Wands",
    nameKo: "지팡이 여왕",
    keyword: "자신감, 매력",
    fortunes: {
      up: "당당한 태도가 주변 사람들에게 좋은 인상을 남깁니다.",
      down: "지금의 자신감을 잃지 않고 꾸준히 나아가면 충분해요.",
      left: "예전부터 다져온 매력이 자연스럽게 빛을 발하고 있어요.",
      right: "예상보다 많은 사람들의 관심과 지지를 받을 수 있어요.",
    },
  },
  {
    number: 35,
    nameEn: "King of Wands",
    nameKo: "지팡이 왕",
    keyword: "리더십, 비전",
    fortunes: {
      up: "큰 그림을 그리며 앞장서 이끌어야 할 순간이 왔습니다.",
      down: "지금의 경험이 흔들림 없는 판단력의 기반이 되어줘요.",
      left: "예전에 쌓은 리더십이 지금 빛을 발할 준비가 됐습니다.",
      right: "갑작스레 중요한 결정을 내려야 할 자리에 서게 될 수 있어요.",
    },
  },
  {
    number: 36,
    nameEn: "Ace of Cups",
    nameKo: "성배 에이스",
    keyword: "새로운 감정",
    fortunes: {
      up: "마음이 벅차오르는 새로운 감정이 찾아올 준비를 하고 있어요.",
      down: "지금의 잔잔한 감정을 있는 그대로 느껴봐도 좋습니다.",
      left: "예전에 느꼈던 설렘이 다시 살아날 수 있어요.",
      right: "예상치 못한 순간에 마음을 사로잡는 인연이 찾아올 수 있어요.",
    },
  },
  {
    number: 37,
    nameEn: "Two of Cups",
    nameKo: "성배 2",
    keyword: "연결, 파트너십",
    fortunes: {
      up: "서로를 이해하는 관계가 한 단계 더 깊어질 수 있어요.",
      down: "지금의 관계를 천천히 다져가는 것만으로도 충분합니다.",
      left: "예전의 인연이 다시 특별한 의미로 다가올 수 있어요.",
      right: "예상치 못한 만남이 좋은 파트너십으로 이어질 수 있어요.",
    },
  },
  {
    number: 38,
    nameEn: "Three of Cups",
    nameKo: "성배 3",
    keyword: "우정, 축하",
    fortunes: {
      up: "소중한 사람들과 함께 기쁨을 나눌 자리가 생길 것 같아요.",
      down: "지금 곁에 있는 사람들의 소중함을 다시금 느끼게 됩니다.",
      left: "예전부터 이어온 우정이 든든한 힘이 되어줍니다.",
      right: "갑작스러운 모임이나 소식이 즐거움을 더해줄 수 있어요.",
    },
  },
  {
    number: 39,
    nameEn: "Four of Cups",
    nameKo: "성배 4",
    keyword: "권태, 재고",
    fortunes: {
      up: "무심코 지나쳤던 기회를 다시 눈여겨볼 필요가 있어요.",
      down: "지금은 잠시 멈춰 마음을 정리하는 시간도 필요합니다.",
      left: "예전의 권태로움이 지금은 새로운 시선으로 바뀔 수 있어요.",
      right: "예상치 못한 제안이 무기력함을 깨워줄 수 있어요.",
    },
  },
  {
    number: 40,
    nameEn: "Five of Cups",
    nameKo: "성배 5",
    keyword: "상실, 후회",
    fortunes: {
      up: "아쉬움 속에서도 아직 남아있는 것들에 눈을 돌려보세요.",
      down: "지금의 서운함도 시간이 지나면 자연스레 옅어질 거예요.",
      left: "예전의 아쉬움을 완전히 흘려보내도 괜찮습니다.",
      right: "예상보다 빨리 마음을 추스르고 다시 일어설 수 있어요.",
    },
  },
  {
    number: 41,
    nameEn: "Six of Cups",
    nameKo: "성배 6",
    keyword: "추억, 향수",
    fortunes: {
      up: "그리운 기억이 지금의 마음을 따뜻하게 채워줍니다.",
      down: "지금 이 순간의 소박한 행복을 충분히 느껴보세요.",
      left: "예전의 좋은 기억이 다시 떠오르며 위로가 되어줍니다.",
      right: "오랜만에 그리운 사람에게서 연락이 올 수 있어요.",
    },
  },
  {
    number: 42,
    nameEn: "Seven of Cups",
    nameKo: "성배 7",
    keyword: "환상, 선택지",
    fortunes: {
      up: "여러 갈래의 가능성 중 마음이 이끄는 쪽을 믿어보세요.",
      down: "지금은 현실적인 기준으로 하나씩 정리해보는 게 좋아요.",
      left: "예전에 품었던 막연한 꿈을 구체화할 시점이 왔어요.",
      right: "예상치 못한 선택지가 갑자기 늘어날 수 있어요.",
    },
  },
  {
    number: 43,
    nameEn: "Eight of Cups",
    nameKo: "성배 8",
    keyword: "떠남, 탐색",
    fortunes: {
      up: "미련 없이 새로운 곳으로 발걸음을 옮길 준비가 됐어요.",
      down: "지금 자리를 정리하며 다음을 준비해도 좋습니다.",
      left: "예전에 두고 온 것에 더 이상 얽매이지 않아도 괜찮아요.",
      right: "갑작스러운 결정이 예상보다 홀가분함을 안겨줄 수 있어요.",
    },
  },
  {
    number: 44,
    nameEn: "Nine of Cups",
    nameKo: "성배 9",
    keyword: "만족, 소원성취",
    fortunes: {
      up: "바라던 일이 마음먹은 대로 이루어질 가능성이 큽니다.",
      down: "지금 가진 것들에 감사하면 만족감이 더 커질 거예요.",
      left: "예전부터 품어온 소원이 조용히 이루어지고 있어요.",
      right: "예상보다 빠르게 기쁜 소식을 듣게 될 수 있어요.",
    },
  },
  {
    number: 45,
    nameEn: "Ten of Cups",
    nameKo: "성배 10",
    keyword: "행복, 화합",
    fortunes: {
      up: "가까운 사람들과의 관계에서 깊은 행복을 느낄 수 있어요.",
      down: "지금의 평온한 일상이 가장 큰 행복임을 깨닫게 됩니다.",
      left: "예전부터 그려온 화목한 그림이 서서히 현실이 되고 있어요.",
      right: "예상치 못한 순간에 마음이 따뜻해지는 일이 생길 수 있어요.",
    },
  },
  {
    number: 46,
    nameEn: "Page of Cups",
    nameKo: "성배 시종",
    keyword: "창의적 소식",
    fortunes: {
      up: "감성을 자극하는 새로운 소식이나 제안이 찾아올 수 있어요.",
      down: "지금 떠오르는 직감을 가볍게 믿어봐도 좋습니다.",
      left: "예전에 품었던 감성적인 꿈이 다시 떠오를 수 있어요.",
      right: "예상치 못한 곳에서 다정한 마음을 전해받을 수 있어요.",
    },
  },
  {
    number: 47,
    nameEn: "Knight of Cups",
    nameKo: "성배 기사",
    keyword: "낭만, 제안",
    fortunes: {
      up: "마음을 설레게 하는 제안이나 고백이 찾아올 수 있어요.",
      down: "지금의 감정을 서두르지 않고 천천히 확인해봐도 좋아요.",
      left: "예전의 낭만적인 순간이 다시 그리워질 수 있어요.",
      right: "갑작스러운 만남이 특별한 인연으로 이어질 수 있어요.",
    },
  },
  {
    number: 48,
    nameEn: "Queen of Cups",
    nameKo: "성배 여왕",
    keyword: "공감, 직관",
    fortunes: {
      up: "따뜻한 공감과 배려가 주변 사람들에게 큰 위로가 됩니다.",
      down: "지금의 직관을 믿고 마음이 이끄는 대로 움직여도 좋아요.",
      left: "예전부터 지녀온 다정함이 지금도 변함없이 빛나고 있어요.",
      right: "예상치 못한 순간에 깊은 이해를 받는 경험을 하게 돼요.",
    },
  },
  {
    number: 49,
    nameEn: "King of Cups",
    nameKo: "성배 왕",
    keyword: "감정적 균형",
    fortunes: {
      up: "흔들리는 감정 속에서도 침착함을 유지하면 좋은 결과가 따라와요.",
      down: "지금의 안정된 마음가짐이 주변에도 좋은 영향을 줍니다.",
      left: "예전의 경험이 지금의 성숙한 판단력으로 이어졌어요.",
      right: "예상보다 어려운 상황에서도 의연하게 대처할 수 있어요.",
    },
  },
  {
    number: 50,
    nameEn: "Ace of Swords",
    nameKo: "검 에이스",
    keyword: "명료함, 돌파구",
    fortunes: {
      up: "복잡했던 생각이 명확해지며 돌파구가 보이기 시작합니다.",
      down: "지금의 차분한 판단력이 문제 해결의 열쇠가 되어줘요.",
      left: "예전부터 고민하던 문제의 답이 서서히 드러나고 있어요.",
      right: "갑작스러운 깨달음이 상황을 단번에 정리해줄 수 있어요.",
    },
  },
  {
    number: 51,
    nameEn: "Two of Swords",
    nameKo: "검 2",
    keyword: "결정 보류, 균형",
    fortunes: {
      up: "미뤄뒀던 결정을 이제는 마주할 준비가 되어가고 있어요.",
      down: "지금은 성급하게 정하지 않고 균형을 유지해도 괜찮습니다.",
      left: "예전부터 이어온 고민을 이제는 정리할 때가 됐어요.",
      right: "예상치 못한 정보가 결정을 도와줄 수 있어요.",
    },
  },
  {
    number: 52,
    nameEn: "Three of Swords",
    nameKo: "검 3",
    keyword: "마음의 상처",
    fortunes: {
      up: "아팠던 마음도 시간이 지나면 서서히 아물어갈 거예요.",
      down: "지금의 아픔을 억누르기보다 있는 그대로 인정해도 괜찮아요.",
      left: "예전의 상처가 지금은 더 단단한 마음으로 남았습니다.",
      right: "갑작스러운 솔직한 대화가 오히려 관계를 회복시켜줄 수 있어요.",
    },
  },
  {
    number: 53,
    nameEn: "Four of Swords",
    nameKo: "검 4",
    keyword: "휴식, 회복",
    fortunes: {
      up: "충분한 휴식 후에 다시 힘차게 나아갈 수 있을 거예요.",
      down: "지금은 무리하지 말고 잠시 멈춰 쉬어가도 좋습니다.",
      left: "예전의 지친 마음이 이제는 서서히 회복되고 있어요.",
      right: "예상치 못한 여유가 갑자기 찾아올 수 있어요.",
    },
  },
  {
    number: 54,
    nameEn: "Five of Swords",
    nameKo: "검 5",
    keyword: "갈등, 손실",
    fortunes: {
      up: "다툼보다 한 걸음 물러서는 것이 더 나은 결과를 만들어요.",
      down: "지금의 갈등도 시간이 지나면 자연스레 정리될 거예요.",
      left: "예전의 다툼에서 얻은 교훈이 지금 도움이 되고 있어요.",
      right: "예상치 못한 화해의 기회가 갑자기 찾아올 수 있어요.",
    },
  },
  {
    number: 55,
    nameEn: "Six of Swords",
    nameKo: "검 6",
    keyword: "전환, 이동",
    fortunes: {
      up: "어려운 시기를 지나 더 편안한 곳으로 나아가고 있어요.",
      down: "지금의 변화가 낯설어도 결국 좋은 방향으로 이어질 거예요.",
      left: "예전에 떠나온 자리가 지금 보면 옳은 선택이었어요.",
      right: "갑작스러운 이동이나 변화가 새로운 안정을 가져다줄 수 있어요.",
    },
  },
  {
    number: 56,
    nameEn: "Seven of Swords",
    nameKo: "검 7",
    keyword: "전략, 회피",
    fortunes: {
      up: "신중한 전략이 지금 상황을 유리하게 이끌어줄 수 있어요.",
      down: "지금은 드러내기보다 조용히 준비하는 편이 나을 수 있어요.",
      left: "예전에 세운 전략이 지금도 여전히 유효합니다.",
      right: "예상치 못한 잔꾀보다 정직한 태도가 더 좋은 결과를 가져와요.",
    },
  },
  {
    number: 57,
    nameEn: "Eight of Swords",
    nameKo: "검 8",
    keyword: "속박, 제한된 생각",
    fortunes: {
      up: "스스로를 가두던 생각에서 벗어날 용기가 필요해요.",
      down: "지금의 답답함도 관점을 바꾸면 실마리가 보일 거예요.",
      left: "예전의 두려움이 지금은 더 이상 걸림돌이 아니에요.",
      right: "예상치 못한 계기로 갑갑했던 상황이 풀려나갈 수 있어요.",
    },
  },
  {
    number: 58,
    nameEn: "Nine of Swords",
    nameKo: "검 9",
    keyword: "불안, 걱정",
    fortunes: {
      up: "걱정이 크게 느껴져도 실제로는 잘 지나갈 가능성이 높아요.",
      down: "지금의 불안한 마음을 혼자 끌어안지 않아도 괜찮습니다.",
      left: "예전의 걱정이 지나고 보면 별일 아니었음을 알게 될 거예요.",
      right: "예상치 못한 안심되는 소식이 불안을 잠재워줄 수 있어요.",
    },
  },
  {
    number: 59,
    nameEn: "Ten of Swords",
    nameKo: "검 10",
    keyword: "끝, 바닥",
    fortunes: {
      up: "힘든 시기가 끝나고 새로운 시작이 기다리고 있어요.",
      down: "지금이 바닥이라면 이제 올라갈 일만 남았습니다.",
      left: "예전의 힘들었던 일은 이제 완전히 매듭지어도 괜찮아요.",
      right: "예상보다 빠르게 상황이 마무리되고 전환점을 맞을 수 있어요.",
    },
  },
  {
    number: 60,
    nameEn: "Page of Swords",
    nameKo: "검 시종",
    keyword: "호기심, 경계",
    fortunes: {
      up: "예리한 관찰력이 유용한 정보를 알아채게 해줄 거예요.",
      down: "지금은 성급히 판단하기보다 좀 더 지켜봐도 좋습니다.",
      left: "예전에 배운 경계심이 지금도 도움이 되고 있어요.",
      right: "예상치 못한 소식이나 소문이 들려올 수 있어요.",
    },
  },
  {
    number: 61,
    nameEn: "Knight of Swords",
    nameKo: "검 기사",
    keyword: "성급함, 추진력",
    fortunes: {
      up: "거침없는 추진력이 목표에 빠르게 다가가게 해줄 거예요.",
      down: "지금은 속도를 늦추고 신중하게 움직이는 게 좋습니다.",
      left: "예전의 성급했던 선택에서 얻은 교훈이 지금 도움이 돼요.",
      right: "갑작스러운 결단이 예상보다 빠른 결과를 만들어낼 수 있어요.",
    },
  },
  {
    number: 62,
    nameEn: "Queen of Swords",
    nameKo: "검 여왕",
    keyword: "명확한 판단",
    fortunes: {
      up: "흔들림 없는 판단력이 복잡한 상황을 정리해줄 거예요.",
      down: "지금의 냉철함이 오히려 주변에 신뢰를 줍니다.",
      left: "예전의 경험에서 얻은 통찰이 지금 빛을 발하고 있어요.",
      right: "예상치 못한 진실이 명확하게 드러날 수 있어요.",
    },
  },
  {
    number: 63,
    nameEn: "King of Swords",
    nameKo: "검 왕",
    keyword: "권위, 논리",
    fortunes: {
      up: "논리적인 접근이 어려운 문제를 명쾌하게 풀어줄 거예요.",
      down: "지금의 원칙을 지키는 태도가 좋은 결과로 이어집니다.",
      left: "예전에 세운 기준이 지금도 흔들림 없이 유효해요.",
      right: "예상치 못한 중요한 결정을 내려야 할 순간이 올 수 있어요.",
    },
  },
  {
    number: 64,
    nameEn: "Ace of Pentacles",
    nameKo: "오망성 에이스",
    keyword: "새로운 기회",
    fortunes: {
      up: "실질적인 기회가 눈앞에 나타나 앞으로의 토대가 되어줄 거예요.",
      down: "지금 다지는 기반이 앞으로 오래도록 든든하게 남습니다.",
      left: "예전에 뿌린 노력의 씨앗이 이제 싹을 틔울 준비를 해요.",
      right: "예상치 못한 곳에서 뜻밖의 제안이 들어올 수 있어요.",
    },
  },
  {
    number: 65,
    nameEn: "Two of Pentacles",
    nameKo: "오망성 2",
    keyword: "균형, 우선순위",
    fortunes: {
      up: "여러 일 사이의 균형을 잘 잡으면 무리 없이 해낼 수 있어요.",
      down: "지금은 우선순위를 다시 정리해보는 것도 좋은 방법이에요.",
      left: "예전부터 이어온 균형 감각이 지금도 도움이 되고 있어요.",
      right: "예상치 못하게 여러 일이 한꺼번에 몰려올 수 있어요.",
    },
  },
  {
    number: 66,
    nameEn: "Three of Pentacles",
    nameKo: "오망성 3",
    keyword: "협업, 숙련",
    fortunes: {
      up: "함께하는 사람들과의 협업이 좋은 결실로 이어질 거예요.",
      down: "지금의 꾸준한 노력이 실력으로 차곡차곡 쌓이고 있어요.",
      left: "예전에 함께한 사람들과의 인연이 다시 이어질 수 있어요.",
      right: "예상치 못한 협업 제안이 좋은 기회가 되어줄 수 있어요.",
    },
  },
  {
    number: 67,
    nameEn: "Four of Pentacles",
    nameKo: "오망성 4",
    keyword: "안정, 집착",
    fortunes: {
      up: "지금 가진 것을 지키려는 마음이 조금은 여유를 가져도 괜찮아요.",
      down: "지금의 안정감을 유지하는 것도 충분히 의미 있는 선택이에요.",
      left: "예전부터 지켜온 것들의 소중함을 다시 느끼게 됩니다.",
      right: "예상치 못한 지출이나 변화에 마음을 열어두는 게 좋아요.",
    },
  },
  {
    number: 68,
    nameEn: "Five of Pentacles",
    nameKo: "오망성 5",
    keyword: "어려움, 결핍",
    fortunes: {
      up: "어려운 시기 속에서도 도움의 손길이 가까이 있을 거예요.",
      down: "지금의 부족함이 오히려 소중한 것을 알아보게 해줍니다.",
      left: "예전의 어려웠던 시절이 지금의 강인함을 만들어줬어요.",
      right: "예상치 못한 도움이 갑작스레 나타날 수 있어요.",
    },
  },
  {
    number: 69,
    nameEn: "Six of Pentacles",
    nameKo: "오망성 6",
    keyword: "나눔, 균형",
    fortunes: {
      up: "주고받는 것의 균형이 맞을 때 관계가 더 편안해집니다.",
      down: "지금 베푸는 마음이 언젠가 좋은 형태로 돌아올 거예요.",
      left: "예전에 받았던 도움을 이제는 갚을 차례일 수 있어요.",
      right: "예상치 못한 도움이나 지원을 받게 될 수 있어요.",
    },
  },
  {
    number: 70,
    nameEn: "Seven of Pentacles",
    nameKo: "오망성 7",
    keyword: "인내, 평가",
    fortunes: {
      up: "조급해하지 않고 기다리면 노력의 결실을 보게 될 거예요.",
      down: "지금은 그동안의 성과를 차분히 점검해보는 시간이에요.",
      left: "예전에 심어둔 노력이 이제 서서히 자라나고 있어요.",
      right: "예상보다 빠르게 결과가 눈에 보이기 시작할 수 있어요.",
    },
  },
  {
    number: 71,
    nameEn: "Eight of Pentacles",
    nameKo: "오망성 8",
    keyword: "숙련, 노력",
    fortunes: {
      up: "꾸준한 연습과 노력이 실력을 한 단계 끌어올려 줄 거예요.",
      down: "지금 하는 반복적인 노력이 결코 헛되지 않습니다.",
      left: "예전부터 갈고닦은 기술이 지금 빛을 발하고 있어요.",
      right: "예상치 못한 배움의 기회가 찾아올 수 있어요.",
    },
  },
  {
    number: 72,
    nameEn: "Nine of Pentacles",
    nameKo: "오망성 9",
    keyword: "풍요, 독립",
    fortunes: {
      up: "스스로 이룬 결실을 온전히 누릴 자격이 충분해요.",
      down: "지금의 여유로움을 자신에게 선물해줘도 좋습니다.",
      left: "예전부터 쌓아온 노력이 지금의 풍요로 돌아왔어요.",
      right: "예상치 못한 뜻밖의 보상이 찾아올 수 있어요.",
    },
  },
  {
    number: 73,
    nameEn: "Ten of Pentacles",
    nameKo: "오망성 10",
    keyword: "유산, 안정",
    fortunes: {
      up: "오랜 노력이 가족이나 공동체의 든든한 기반이 되어줄 거예요.",
      down: "지금의 안정이 앞으로도 오래도록 이어질 가능성이 커요.",
      left: "예전부터 쌓아온 것들이 지금의 든든함으로 남았습니다.",
      right: "예상치 못한 곳에서 뜻깊은 유산이나 기회를 얻을 수 있어요.",
    },
  },
  {
    number: 74,
    nameEn: "Page of Pentacles",
    nameKo: "오망성 시종",
    keyword: "배움, 계획",
    fortunes: {
      up: "새로운 배움이나 계획이 실질적인 결실로 이어질 수 있어요.",
      down: "지금 차근차근 세우는 계획이 든든한 토대가 되어줍니다.",
      left: "예전에 세워둔 목표를 다시 점검해볼 시점이에요.",
      right: "예상치 못한 배움의 기회나 제안이 찾아올 수 있어요.",
    },
  },
  {
    number: 75,
    nameEn: "Knight of Pentacles",
    nameKo: "오망성 기사",
    keyword: "근면, 신중함",
    fortunes: {
      up: "꾸준하고 성실한 태도가 결국 좋은 결과로 이어질 거예요.",
      down: "지금의 신중함이 실수를 줄이고 안정을 가져다줍니다.",
      left: "예전부터 지켜온 성실함이 지금의 신뢰로 이어졌어요.",
      right: "예상보다 느리더라도 확실한 진전을 이룰 수 있어요.",
    },
  },
  {
    number: 76,
    nameEn: "Queen of Pentacles",
    nameKo: "오망성 여왕",
    keyword: "실용성, 풍요",
    fortunes: {
      up: "현실적인 감각이 안정과 풍요를 동시에 가져다줄 거예요.",
      down: "지금 돌보고 있는 것들에 정성을 쏟으면 좋은 결실이 와요.",
      left: "예전부터 다져온 살림살이의 지혜가 지금도 빛을 발해요.",
      right: "예상치 못한 풍족함이나 안정이 찾아올 수 있어요.",
    },
  },
  {
    number: 77,
    nameEn: "King of Pentacles",
    nameKo: "오망성 왕",
    keyword: "성공, 안정된 부",
    fortunes: {
      up: "그동안 쌓아온 노력이 확고한 성공으로 자리 잡을 거예요.",
      down: "지금의 안정된 기반이 앞으로도 든든하게 이어집니다.",
      left: "예전부터 다져온 기반이 지금의 성공을 뒷받침해줘요.",
      right: "예상치 못한 큰 성과나 인정을 받게 될 수 있어요.",
    },
  },
];

export function shuffleCards(cards: TarotCard[]): TarotCard[] {
  const result = [...cards];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

export const FAN_SIZE = 20;

export function buildFanDeck(pool: TarotCard[], exclude: Set<number>, count: number = FAN_SIZE): TarotCard[] {
  const remaining = pool.filter((c) => !exclude.has(c.number));
  return shuffleCards(remaining).slice(0, count);
}
